Middle section
willy836/Portfolio pull request #2
Opened 2022-08-20 19:00 UTC by willy836

This is the middle section of the portfolio mobile first website. It has the following sections:
  1.Work section
  2. About myselft section
  3. Contact section

2022-08-20 19:05 UTC, willy836 commented
This project doesnt pass all linter errors. I wasn't able to fix 2 kinds of errors:
1. Errors in css about no-descending-specificity
2. An error of including an icon in ul list. I didnt know how else to include that icon in my project.

2022-08-20 19:13 UTC, Ismailco reviewed
Hi @willy836, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has some linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-23 05:55 UTC, Nemwel-Boniface requested changes
## Hello @willy836           :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

You have done a great job with your portfolio project so far! :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 05:55 UTC, Nemwel-Boniface commented on index.html
> +                        <button>See Project</button>
- [ ] Great job implementing the button states of hover, click, active, etc. There is something very small left to make it very perfect. Kindly use the colors for the button states which are specified in the chosen Figma design. 

**Below I will include the screenshot for the button states colors:**

![image](https://user-images.githubusercontent.com/86318284/186078523-5e8282fd-202a-460f-9691-f75c00d8a88c.png)

**Kindly implement this change in all your buttons as I have realised that the trend is the same in all your buttons.**

2022-08-23 05:55 UTC, Nemwel-Boniface commented on index.html
> +                    <h1>About<br> Myself</h1>
- [ ] Great job using a header element for this part :clap: . However note for semantic reasons, it is not recommended to have more than one ```<h1>``` tags per webpage. This in mind, kindly change this from a h1 to a hx. ```<h2>``` would be a better option for this.

2022-08-23 05:55 UTC, Nemwel-Boniface commented on index.html
> +                    <h2 class="text">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a pro
- [ ] It would be rather semantically correct to make this a paragraph than a header. It is more of an "explanatory" than a heading. Kindly change this.

2022-08-23 05:55 UTC, Nemwel-Boniface commented on index.html
> +                        <hr>
- [ ] I have realized that the ```<hr>``` is having a line through the page which is not supposed to be visible according to the chosen Figma design. It would be a good thing to play with the colors and give it a color that matches ```background: #DFE1E6;``` which will ensure that it is not fully visible and looks like the chosen Figma design. 

**This is how I am seeing this section:**

![image](https://user-images.githubusercontent.com/86318284/186080589-a20865dc-826c-4b3b-9f6e-bc5a78844080.png)

**This is how it is supposed to be in the Figma design:**

![image](https://user-images.githubusercontent.com/86318284/186080671-33090dd4-1dea-461c-9d38-8d49977bd4b3.png)

2022-08-23 05:55 UTC, Nemwel-Boniface commented on index.html
> +                        <hr>
- [ ] I have realized that the ```<hr>``` is having a line through the page which is not supposed to be visible according to the chosen Figma design. It would be a good thing to play with the colors and give it a color that matches ```background: #DFE1E6;``` which will ensure that it is not fully visible and looks like the chosen Figma design. 

**This is how I am seeing this section:**

![image](https://user-images.githubusercontent.com/86318284/186080589-a20865dc-826c-4b3b-9f6e-bc5a78844080.png)

**This is how it is supposed to be in the Figma design:**

![image](https://user-images.githubusercontent.com/86318284/186080671-33090dd4-1dea-461c-9d38-8d49977bd4b3.png)

2022-08-23 13:54 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @willy836👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 14:14 UTC, merged